# Data source collection
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/abitoflink?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B11
    username: root
    password: your-production-env-db-password

rules:
  - !SHARDING
    tables:
      t_link:
        # Real data nodes, such as database sources and databases that actually exist in the database
        actualDataNodes: ds_0.t_link_${0..15}
        # Table strategy
        tableStrategy:
          # For standard sharding scenarios with a single sharding key
          standard:
            # Sharding key
            shardingColumn: gid
            # Sharding algorithm, corresponding to rules[0].shardingAlgorithms
            shardingAlgorithmName: link_table_hash_mod
      t_link_goto:
        # Real data nodes, such as database sources and databases that actually exist in the database
        actualDataNodes: ds_0.t_link_goto_${0..15}
        # Table strategy
        tableStrategy:
          # For standard sharding scenarios with a single sharding key
          standard:
            # Sharding key
            shardingColumn: full_short_url
            # Sharding algorithm, corresponding to rules[0].shardingAlgorithms
            shardingAlgorithmName: link_goto_table_hash_mod
      t_link_stats_today:
        # Real data nodes, such as database sources and databases that actually exist in the database
        actualDataNodes: ds_0.t_link_stats_today_${0..15}
        # Table strategy
        tableStrategy:
          # For standard sharding scenarios with a single sharding key
          standard:
            # Sharding key
            shardingColumn: gid
            # Sharding algorithm, corresponding to rules[0].shardingAlgorithms
            shardingAlgorithmName: link_stats_today_table_hash_mod
    # Binding tables
    bindingTables:
      - t_link, t_link_stats_today
    # Sharding algorithm
    shardingAlgorithms:
      # Data table sharding algorithm
      link_table_hash_mod:
        # Shard by hash of sharding key
        type: HASH_MOD
        # Number of shards
        props:
          sharding-count: 16
      link_goto_table_hash_mod:
        # Shard by hash of sharding key
        type: HASH_MOD
        # Number of shards
        props:
          sharding-count: 16
      link_stats_today_table_hash_mod:
        # Shard by hash of sharding key
        type: HASH_MOD
        # Number of shards
        props:
          sharding-count: 16
# Display logical SQL & real SQL
props:
  sql-show: true